In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
# Set random seeds to ensure that the results are repeatable with each run.
seed = 42
np.random.seed(seed)

In [3]:
# Import Dataset
all_data = pd.read_excel("../data/CustomerChurn.xlsx")
# Remove the customer ID labels
all_data.drop(["LoyaltyID", "Customer ID"], axis = 1, inplace = True)
# Display the data
all_data.head()

,Senior Citizen,Partner,Dependents,Tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,No,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Senior Citizen     7043 non-null   object
 1   Partner            7043 non-null   object
 2   Dependents         7043 non-null   object
 3   Tenure             7043 non-null   int64
 4   Phone Service      7043 non-null   object
 5   Multiple Lines     7043 non-null   object
 6   Internet Service   7043 non-null   object
 7   Online Security    7043 non-null   object
 8   Online Backup      7043 non-null   object
 9   Device Protection  7043 non-null   object
 10  Tech Support       7043 non-null   object
 11  Streaming TV       7043 non-null   object
 12  Streaming Movies   7043 non-null   object
 13  Contract           7043 non-null   object
 14  Paperless Billing  7043 non-null   object
 15  Payment Method     7043 non-null   object
 16  Monthly Charges    7043 non-null   float64
 17  Total Charges      7043 non-null   object
 18  Churn              7043 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 1.0+ MB

In [5]:
sum(all_data["Total Charges"] == ' ')

11

In [6]:
all_data[all_data["Total Charges"] == " "]

,Senior Citizen,Partner,Dependents,Tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
488,No,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,No,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,No,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,No,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

There's 11 of the above... let's just get rid of them.

In [7]:
all_data.drop(all_data[all_data["Total Charges"] == " "].index, inplace = True)
all_data.reset_index(drop = True, inplace = True)
sum(all_data["Total Charges"] == ' ')

0

In [8]:
all_data["Total Charges"] = all_data["Total Charges"].astype(float)
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Senior Citizen     7032 non-null   object
 1   Partner            7032 non-null   object
 2   Dependents         7032 non-null   object
 3   Tenure             7032 non-null   int64
 4   Phone Service      7032 non-null   object
 5   Multiple Lines     7032 non-null   object
 6   Internet Service   7032 non-null   object
 7   Online Security    7032 non-null   object
 8   Online Backup      7032 non-null   object
 9   Device Protection  7032 non-null   object
 10  Tech Support       7032 non-null   object
 11  Streaming TV       7032 non-null   object
 12  Streaming Movies   7032 non-null   object
 13  Contract           7032 non-null   object
 14  Paperless Billing  7032 non-null   object
 15  Payment Method     7032 non-null   object
 16  Monthly Charges    7032 non-null   float64
 17  Total Charges      7032 non-null   float64
 18  Churn              7032 non-null   object
dtypes: float64(2), int64(1), object(16)
memory usage: 1.0+ MB

In [9]:
for col in all_data.columns:
    if all_data[col].dtype == 'object':
        print("------------")
        print(all_data[col].value_counts())

------------
Senior Citizen
No     5890
Yes    1142
Name: count, dtype: int64
------------
Partner
No     3639
Yes    3393
Name: count, dtype: int64
------------
Dependents
No     4933
Yes    2099
Name: count, dtype: int64
------------
Phone Service
Yes    6352
No      680
Name: count, dtype: int64
------------
Multiple Lines
No                  3385
Yes                 2967
No phone service     680
Name: count, dtype: int64
------------
Internet Service
Fiber optic    3096
DSL            2416
No             1520
Name: count, dtype: int64
------------
Online Security
No                     3497
Yes                    2015
No internet service    1520
Name: count, dtype: int64
------------
Online Backup
No                     3087
Yes                    2425
No internet service    1520
Name: count, dtype: int64
------------
Device Protection
No                     3094
Yes                    2418
No internet service    1520
Name: count, dtype: int64
------------
Tech Support
No                     3472
Yes                    2040
No internet service    1520
Name: count, dtype: int64
------------
Streaming TV
No                     2809
Yes                    2703
No internet service    1520
Name: count, dtype: int64
------------
Streaming Movies
No                     2781
Yes                    2731
No internet service    1520
Name: count, dtype: int64
------------
Contract
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64
------------
Paperless Billing
Yes    4168
No     2864
Name: count, dtype: int64
------------
Payment Method
Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: count, dtype: int64
------------
Churn
No     5163
Yes    1869
Name: count, dtype: int64

The values "No internet service" and "No phone service" in certain columns are because of a respective value in another column within the same dataset. These values do not need to be represented. However, the columns that they are in are otherwise Yes/No columns that can be turned into binary. These values can be removed by turning them into "No".

In [10]:
# Remove the impresent phrases within the dataframe
all_data = all_data.replace(["No internet service", "No phone service"], "No")

In [11]:
# Before proceeding, we need to turn all the object values into int
for col in all_data.columns:
    # We can start by changing Yes/No into True/False
    if all_data[col].nunique() == 2:
        all_data[col] = all_data[col].replace({'Yes': True, 'No': False})

C:\Users\manub\AppData\Local\Temp\ipykernel_10304\999685621.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  all_data[col] = all_data[col].replace({'Yes': True, 'No': False})

In [12]:
for col in all_data.columns:
    if all_data[col].dtype == 'object':
        print("------------")
        print(col)
        print(all_data[col].unique())

------------
Internet Service
['DSL' 'Fiber optic' 'No']
------------
Contract
['Month-to-month' 'One year' 'Two year']
------------
Payment Method
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [13]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Senior Citizen     7032 non-null   bool
 1   Partner            7032 non-null   bool
 2   Dependents         7032 non-null   bool
 3   Tenure             7032 non-null   int64
 4   Phone Service      7032 non-null   bool
 5   Multiple Lines     7032 non-null   bool
 6   Internet Service   7032 non-null   object
 7   Online Security    7032 non-null   bool
 8   Online Backup      7032 non-null   bool
 9   Device Protection  7032 non-null   bool
 10  Tech Support       7032 non-null   bool
 11  Streaming TV       7032 non-null   bool
 12  Streaming Movies   7032 non-null   bool
 13  Contract           7032 non-null   object
 14  Paperless Billing  7032 non-null   bool
 15  Payment Method     7032 non-null   object
 16  Monthly Charges    7032 non-null   float64
 17  Total Charges      7032 non-null   float64
 18  Churn              7032 non-null   bool
dtypes: bool(13), float64(2), int64(1), object(3)
memory usage: 419.0+ KB

The only object columns left are Internet Service, Contract, and Payment Method. These can be one-hot encoded.

In [14]:
onehotcols = ["Internet Service", "Contract", "Payment Method"]

# Get the dummies of these ones
df = pd.get_dummies(all_data, columns=onehotcols, drop_first=False)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Senior Citizen                            7032 non-null   bool
 1   Partner                                   7032 non-null   bool
 2   Dependents                                7032 non-null   bool
 3   Tenure                                    7032 non-null   int64
 4   Phone Service                             7032 non-null   bool
 5   Multiple Lines                            7032 non-null   bool
 6   Online Security                           7032 non-null   bool
 7   Online Backup                             7032 non-null   bool
 8   Device Protection                         7032 non-null   bool
 9   Tech Support                              7032 non-null   bool
 10  Streaming TV                              7032 non-null   bool
 11  Streaming Movies                          7032 non-null   bool
 12  Paperless Billing                         7032 non-null   bool
 13  Monthly Charges                           7032 non-null   float64
 14  Total Charges                             7032 non-null   float64
 15  Churn                                     7032 non-null   bool
 16  Internet Service_DSL                      7032 non-null   bool
 17  Internet Service_Fiber optic              7032 non-null   bool
 18  Internet Service_No                       7032 non-null   bool
 19  Contract_Month-to-month                   7032 non-null   bool
 20  Contract_One year                         7032 non-null   bool
 21  Contract_Two year                         7032 non-null   bool
 22  Payment Method_Bank transfer (automatic)  7032 non-null   bool
 23  Payment Method_Credit card (automatic)    7032 non-null   bool
 24  Payment Method_Electronic check           7032 non-null   bool
 25  Payment Method_Mailed check               7032 non-null   bool
dtypes: bool(23), float64(2), int64(1)
memory usage: 322.9 KB

In [16]:
# Save the data
df.to_csv("../data/preprocessed.csv", index = False)